web:
  ingress:
    enabled: true
    className: traefik
    host: openvisualregression.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - hosts: [openvisualregression.com]
        secretName: ovr-tls
