apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ovr-data
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/open-visual-regression/manifests.git
    targetRevision: main
    path: data
    directory:
      recurse: false
  destination:
    name: vultr
    namespace: ovr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
