apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ovr-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/open-visual-regression/manifests.git
    targetRevision: main
    path: helm/ovr
    helm:
      valueFiles:
        - values-vultr.yaml
  destination:
    name: vultr
    namespace: ovr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
